routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('example');
});


Route::prefix('admin')->group(function () {
    Route::resource('/donors', 'Admin\DonorsController');
	Route::resource('/provinces', 'Admin\ProvincesController');
});

Route::get('/admin/home', [
	'uses'	=>	'Admin\HomeController@index',
	'as'	=>	'home'
]);
// Route::get('/admin/patients', [
// 	'uses'	=>	'Admin\PatientsController@index',
// 	'as'	=>	'patients'
// ]);

Route::prefix('admin')->group(function () {
	Route::resource('/patients', 'Admin\PatientsController');
});

app/Http/Controllers/Admin/DonorsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Donor;

class DonorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $donors = Donor::orderBy('created_at', 'desc')->paginate(10);
        $itemCount = Donor::count();

        return view('admin.donors.index', compact('donors', 'itemCount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $donors = new Donor();
        return view('admin.donors.create', compact('donors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\DonorStoreRequest $request)
    {
    
        Donor::create($request->all());

        return redirect('admin\donors');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $donors = Donor::findOrFail($id);
        return view('admin.donors.edit', compact('donors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\DonorUpdateRequest $request, $id)
    {
        $request->merge([
            'id_masjid' => session('id_masjid'),
            'id_user' => session('id_user'),
        ]);

        Donor::findOrFail($id)->update($request->all());


        return redirect('admin\donors');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Donor::findOrFail($id)->delete();


        return redirect('admin/donors');
    }
}

resources/views/admin/donors/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Pendonor')

@section('content')
<div class="content-wrapper">

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pendonor
      <small>Mendata Pendonor</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('donors.index') }}">Pendonor</a></li>
      <li class="active">Tambah Pendonor</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">

      {!! Form::model($donors, [
        'method'  => 'POST',
        'route'   => 'donors.store',
        'id'      => 'donor-form'
      ]) !!}

      @include('admin.donors.form')

      {!! Form::close() !!}

    </div>

  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/donors/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edit Pendonor')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pendonor
      <small>Mendata Pendonor</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('donors.index') }}">Pendonor</a></li>
      <li class="active">Edit Pendonor</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">

      {!! Form::model($donors, [
        'method'  => 'PUT',
        'route'   => ['donors.update', $donors->id],
        'id'      => 'donor-form'
      ]) !!}

      @include('admin.donors.form')

      {!! Form::close() !!}

    </div>

  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/donors/form.blade.php
<div class="col-md-9">
  <!-- Default box -->
  <div class="box">

    <div class="box-header with-border">
      <h3 class="box-title">{{ $donors->exists ? 'Edit' : 'Tambah' }} Donasi</h3>
      <span class="text-muted small pull-right">kolom yang memiliki tanda ( * ) wajib diisi!</span>
    </div>

    <!-- box-body -->
    <div class="box-body">
      <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
        {!! Form::label('Nama') !!}
        <span class="text-primary"> *<span>
        {!! Form::text('name', null,  ['class' => 'form-control', 'id' => 'name']) !!}

        @if ($errors->has('name'))
          <span class="help-block">{{ $errors->first('name') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
        {!! Form::label('Email') !!}
        <span class="text-primary"> *<span>
        {!! Form::email('email', null,  ['class' => 'form-control', 'id' => 'email']) !!}

        @if ($errors->has('email'))
          <span class="help-block">{{ $errors->first('email') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
        {!! Form::label('Password') !!}
        <span class="text-primary"> *<span><br>
        {!! Form::password('password', null,  ['class' => 'form-control', 'id' => 'password']) !!}

        @if ($errors->has('password'))
          <span class="help-block">{{ $errors->first('password') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
        {!! Form::label('No Hp') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('phone', null,  ['class' => 'form-control', 'id' => 'phone']) !!}

        @if ($errors->has('phone'))
          <span class="help-block">{{ $errors->first('phone') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('blod_type') ? 'has-error' : '' }}">
        {!! Form::label('Jenis Darah') !!}
        <span class="text-primary"> *<span>
        {!! Form::select('blod_type', ['A' => 'A', 'B' => 'B', 'AB' => 'AB', 'O' => 'O' ], null,  ['class' => 'form-control', 'id' => 'blod_type']) !!}

        @if ($errors->has('blod_type'))
          <span class="help-block">{{ $errors->first('blod_type') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('province_id') ? 'has-error' : '' }}">
        {!! Form::label('Nama Provinsi') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('province_id', null,  ['class' => 'form-control', 'id' => 'province_id']) !!}

        @if ($errors->has('province_id'))
          <span class="help-block">{{ $errors->first('province_id') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        {!! Form::label('Latitud') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('latitude', null,  ['class' => 'form-control', 'id' => 'latitude']) !!}

        @if ($errors->has('latitude'))
          <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('longitude') ? 'has-error' : '' }}">
        {!! Form::label('Longitud') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('longitude', null,  ['class' => 'form-control', 'id' => 'longitude']) !!}

        @if ($errors->has('longitude'))
          <span class="help-block">{{ $errors->first('longitude') }}</span>
        @endif
      </div>
 
    </div>
    <!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary" id="save-btn">{{ $donors->exists ? 'Perbarui' : 'Simpan' }}</button>
      <a href="{{ route('donors.index') }}" class="btn btn-default">Batal</a>
    </div>

  </div>
  <!-- /.box -->
</div>

resources/views/admin/donors/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Pendonor')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pendonor
      <small>Mendata Pendonor</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('donors.index') }}">Pendonor</a></li>
      <li class="active">Daftar Pendonor</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <a href="{{ route('donors.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Baru</a>
      </div>
      <div class="box-body table-responsive">
        @include('admin.donors.table')
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="pull-left">
          {{ $donors->links() }}
        </div>
        <div class="item-count pull-right text-muted small">
          total {{ $itemCount." ".str_plural('item', $itemCount) }} 
        </div>
      </div>
    </div>
  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/donors/table.blade.php
<table class="table table-hover">
  
  <tr>
    <th width="40">No</th>
    <th>Nama</th>
    <th>No Hp</th>
    <th>Jenis Darah</th>
    <th>Tanggal</th>
    <th>action</th>
  </tr>
  <?php $no = 1; ?>
  @foreach($donors as $donor)
    <tr>
      <td>{{$no++}}</td>
      <td>{{$donor->name}}</td>
      <td>{{$donor->phone}}</td>
      <td>{{$donor->blod_type}}</td>
      <td>{{$donor->created_at}}</td>
      <td>
        <form action=" {{ route('donors.destroy', $donor->id) }} " method="post">
          {{ csrf_field() }}
          {{ method_field("DELETE") }}
          <a href="{{route('donors.edit', $donor->id)}}" class="btn btn-xs btn-primary">
            <i class="fa fa-edit"></i> Edit
          </a>
          <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-xs btn-danger">
            <i class="fa fa-trash"></i> Hapus
          </button>
        </form>
      </td>
    </tr>
  @endforeach

</table>