routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('example');
});


Route::prefix('admin')->group(function () {
    Route::resource('/donors', 'Admin\DonorsController');
	Route::resource('/provinces', 'Admin\ProvincesController');
});

Route::get('/admin/home', [
	'uses'	=>	'Admin\HomeController@index',
	'as'	=>	'home'
]);
// Route::get('/admin/patients', [
// 	'uses'	=>	'Admin\PatientsController@index',
// 	'as'	=>	'patients'
// ]);

Route::prefix('admin')->group(function () {
	Route::resource('/patients', 'Admin\PatientsController');
});

app/Http/Controllers/Admin/ProvincesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Province;

class ProvincesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $provinces = Province::paginate(10);
        $itemCount = Province::count();

        return view('admin.provinces.index', compact('provinces', 'itemCount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $provinces = new Province();
        return view('admin.provinces.create', compact('provinces'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\ProvinceStoreRequest $request)
    {

        Province::create($request->all());

        return redirect('admin\provinces');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $provinces = Province::findOrFail($id);
        return view('admin.provinces.edit', compact('provinces'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\ProvinceUpdateRequest $request, $id)
    {

        Province::findOrFail($id)->update($request->all());

        return redirect('admin\provinces');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Province::findOrFail($id)->delete();

        return redirect('admin/provinces');
    }
}

resources/views/admin/provinces/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edit Provinsi')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Provinsi
      <small>Mendata Provinsi</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('provinces.index') }}">Provinsi</a></li>
      <li class="active">Edit Provinsi</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">

      {!! Form::model($provinces, [
        'method'  => 'PUT',
        'route'   => ['provinces.update', $provinces->id],
        'id'      => 'charity-form'
      ]) !!}

      @include('admin.provinces.form')

      {!! Form::close() !!}

    </div>

  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/provinces/form.blade.php
<div class="col-md-9">
  <!-- Default box -->
  <div class="box">

    <div class="box-header with-border">
      <h3 class="box-title">{{ $provinces->exists ? 'Edit' : 'Tambah' }} Tagihan</h3>
      <span class="text-muted small pull-right">kolom yang memiliki tanda ( * ) wajib diisi!</span>
    </div>

    <!-- box-body -->
    <div class="box-body">
      <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
        {!! Form::label('Nama Province') !!}
        <span class="text-primary"> *<span>
        {!! Form::text('name', null,  ['class' => 'form-control', 'id' => 'name']) !!}

        @if ($errors->has('name'))
          <span class="help-block">{{ $errors->first('name') }}</span>
        @endif
      </div>


      <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        {!! Form::label('Latitude') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('latitude', null,  ['class' => 'form-control', 'id' => 'latitude']) !!}

        @if ($errors->has('latitude'))
          <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
      </div>

      <div class="form-group {{ $errors->has('longitude') ? 'has-error' : '' }}">
        {!! Form::label('Longitude') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('longitude', null,  ['class' => 'form-control', 'id' => 'longitude']) !!}

        @if ($errors->has('longitude'))
          <span class="help-block">{{ $errors->first('longitude') }}</span>
        @endif
      </div>

      
    </div>
    <!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary" id="save-btn">{{ $provinces->exists ? 'Perbarui' : 'Simpan' }}</button>
      <a href="{{ route('provinces.index') }}" class="btn btn-default">Batal</a>
    </div>

  </div>
  <!-- /.box -->
</div>

resources/views/admin/provinces/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Provinsi')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Provinsi
      <small>Mendata riwayat Provinsi</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('provinces.index') }}">Provinsi</a></li>
      <li class="active">Daftar Provinsi</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="box">      
      <div class="box-body table-responsive">

        @include('admin.provinces.table')
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="pull-right text-muted small">
          {{ $provinces->links() }}
        </div>
        <div class="pull-left text-muted small">
          total {{ $itemCount." ".str_plural('item', $itemCount) }} 
        </div>
      </div>
    </div>
  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/provinces/table.blade.php
<table class="table table-hover">
  
  <tr>
    <th width="40">#</th>
    <th>Nama</th>
    <th>Latitude</th>
    <th width="200">Longitude</th>
    <th>Action</th>
  </tr>

  <?php $no = 1; ?>
  @foreach($provinces as $index => $province)
    <tr>
      <td> {{$index + $provinces->firstItem()}} </td>
      <td> {{$province->name}} </td>
      <td> {{$province->latitude}} </td>
      <td> {{$province->longitude}} </td>
      <td>
        <form action=" {{ route('provinces.destroy', $province->id) }} " method="post">
          {{ csrf_field() }}
          {{ method_field("DELETE") }}
          <a href="{{route('provinces.edit', $province->id)}}" class="btn btn-xs btn-primary">
            <i class="fa fa-edit"></i> Edit
          </a>
          <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-xs btn-danger">
            <i class="fa fa-trash"></i> Hapus
          </button>
        </form>
     
    </tr>
  @endforeach

</table>