routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('example');
});


Route::prefix('admin')->group(function () {
    Route::resource('/donors', 'Admin\DonorsController');
	Route::resource('/provinces', 'Admin\ProvincesController');
});

Route::get('/admin/home', [
	'uses'	=>	'Admin\HomeController@index',
	'as'	=>	'home'
]);
// Route::get('/admin/patients', [
// 	'uses'	=>	'Admin\PatientsController@index',
// 	'as'	=>	'patients'
// ]);

Route::prefix('admin')->group(function () {
	Route::resource('/patients', 'Admin\PatientsController');
});

app/Http/Controllers/Admin/PatientsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Province;
use App\Model\BloodType;
use App\Model\Patien;
use App\Http\Requests;

class PatientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $patients = Patien::orderBy('created_at', 'desc')->paginate(8);
        $itemCount = Patien::count();

        return view('admin.patients.index', compact('patients', 'itemCount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $patient = new Patien();
        $province = Province::orderBy('name', 'asc')->pluck('name', 'id')->toArray();
        $result = collect($province)->prepend('Silahkan Pilih', 0);
        $blood = BloodType::orderBy('name')->pluck('name', 'id')->toArray();
        return view('admin.patients.create', compact('patient', 'result', 'blood'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\PatientsStoreRequest $request)
    {
        Patien::create($request->all());

        return redirect('admin\patients');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $patient = Patien::findOrFail($id);
        $province = Province::orderBy('name', 'asc')->pluck('name', 'id')->toArray();
        $result = collect($province)->prepend('Silahkan Pilih', 0);
        $blood = BloodType::orderBy('name')->pluck('name', 'id')->toArray();
        return view('admin.patients.edit', compact('patient', 'result', 'blood'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\PatientsUpdateRequest $request, $id)
    {
        Patien::findOrFail($id)->update($request->all());

        return redirect('admin\patients');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Patien::findOrFail($id)->delete();
        return redirect('admin/patients');
    }
}

resources/views/admin/patients/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Tambah Pasien Donor')

@section('content')
<div class="content-wrapper">

  <!-- Content Header (Page header) -->
  <section class="content-header">
     <h1>
      Pasien
      <small>Mendata Pasien Donor Darah</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('patients.index') }}">Pasien</a></li>
      <li class="active">Tambah Daftar Pasien</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">

      {!! Form::model($patient, [
        'method'  => 'POST',
        'route'   => 'patients.store',
        'id'      => 'patient-form'
      ]) !!}

      @include('admin.patients.form')

      {!! Form::close() !!}

    </div>

  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/patients/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edit Pasien Donor')

@section('content')
<div class="content-wrapper">

  <!-- Content Header (Page header) -->
  <section class="content-header">
     <h1>
      Pasien
      <small>Mendata Pasien Donor Darah</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('home') }}"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ route('patients.index') }}">Pasien</a></li>
      <li class="active">Edit Daftar Pasien</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">

      {!! Form::model($patient, [
        'method'  => 'PUT',
        'route'   => ['patients.update', $patient->id],
        'id'      => 'patient-form'
      ]) !!}

      @include('admin.patients.form')

      {!! Form::close() !!}

    </div>

  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/patients/form.blade.php
<div class="col-md-9">
  <!-- Default box -->
  <div class="box">

    <div class="box-header with-border">
      <h3 class="box-title">{{ $patient->exists ? 'Edit' : 'Tambah' }} Pasien</h3>
      <span class="text-muted small pull-right">kolom yang memiliki tanda ( * ) wajib diisi!</span>
    </div>

    <!-- box-body -->
    <div class="box-body">

      <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
        {!! Form::label('Nama') !!}
        <span class="text-primary"> *<span>
        {!! Form::text('name', null,  ['class' => 'form-control', 'id' => 'name']) !!}

        @if ($errors->has('name'))
          <span class="help-block">{{ $errors->first('name') }}</span>
        @endif
      </div>
      <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
        {!! Form::label('No Telepon') !!}
        <span class="text-primary"> *<span>
        {!! Form::number('phone', null,  ['class' => 'form-control', 'id' => 'phone']) !!}

        @if ($errors->has('phone'))
          <span class="help-block">{{ $errors->first('phone') }}</span>
        @endif
      </div>
      <div class="form-group {{ $errors->has('province_id') ? 'has-error' : '' }}">
        {!! Form::label('ID Provinsi') !!}
        <span class="text-primary"> *<span>
        {!! Form::select('province_id', $result, null,  ['class' => 'form-control', 'id' => 'province_id', 'minlength' => 2, 'maxlength' => 2]) !!}

        @if ($errors->has('province_id'))
          <span class="help-block">{{ $errors->first('province_id') }}</span>
        @endif
      </div>
      <div class="form-group {{ $errors->has('longitude') ? 'has-error' : '' }}">
        {!! Form::label('Longitude') !!}
        <span class="text-primary"> *<span>
        {!! Form::text('longitude', null,  ['class' => 'form-control', 'id' => 'longitude']) !!}

        @if ($errors->has('longitude'))
          <span class="help-block">{{ $errors->first('longitude') }}</span>
        @endif
      </div>
      <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        {!! Form::label('Latitude') !!}
        <span class="text-primary"> *<span>
        {!! Form::text('latitude', null,  ['class' => 'form-control', 'id' => 'latitude']) !!}

        @if ($errors->has('latitude'))
          <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
      </div>
      <div class="form-group {{ $errors->has('blood_type_id') ? 'has-error' : '' }}">
        {!! Form::label('Golongan Darah') !!}
        <span class="text-primary"> *<span>
        {!! Form::select('blood_type_id', $blood, null,  ['class' => 'form-control', 'id' => 'blood_type_id']) !!}

        @if ($errors->has('blood_type_id'))
          <span class="help-block">{{ $errors->first('blood_type_id') }}</span>
        @endif
      </div>

    </div>
    <!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary" id="save-btn">{{ $patient->exists ? 'Perbarui' : 'Simpan' }}</button>
      <a href="{{ route('patients.index') }}" class="btn btn-default">Batal</a>
    </div>

  </div>
  <!-- /.box -->
</div>

resources/views/admin/patients/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Pasien')

@section('style')
<style type="text/css">
  .pagination {
    margin: 0px;
  }
  .item-count {
    margin-top: 5px;
  }
</style>
@endsection

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Pasien
      <small>Mendata Pasien</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="#}">Pasien</a></li>
      <li class="active">Daftar Pasien</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <a href="{{route('patients.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Baru</a>
      </div>
      <div class="box-body table-responsive">
        @include('admin.patients.table')
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="pull-left">
          {{ $patients->links() }}
        </div>
        <div class="item-count pull-right text-muted small">
          total {{ $itemCount." ".str_plural('item', $itemCount) }}
        </div>
      </div>
    </div>
  </section>
  <!-- /.content -->
</div>

@endsection

resources/views/admin/patients/table.blade.php
<table class="table table-hover">
  
  <tr>
    <th width="40">#</th>
    <th width="200">Nama Pasien</th>
    <th>Golongan Darah</th>
    <th>No Telepon</th>
    <th width="150">Action</th>
  </tr>

  <?php $no = 1; ?>
  @foreach($patients as $patient)
    <tr>
      <td>{{ $no++ }}</td>
      <td>{{ $patient->name }}</td>
      <td>{{ $patient->blood_type->name }}</td>
      <td>{{ $patient->phone }}</td>
      <td>
        <form action="{{ route('patients.destroy', $patient->id) }}" method="post">
          {{ csrf_field() }}
          {{ method_field("DELETE") }}
          <a href="{{route('patients.edit', $patient->id)}}" class="btn btn-xs btn-primary">
            <i class="fa fa-edit"></i> Edit
          </a>
          <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-xs btn-danger">
            <i class="fa fa-trash"></i> Hapus
          </button>
        </form>
      </td>
    </tr>
  @endforeach

</table>